language: csharp
mono: none
dotnet: 3.1.202
script:
 - dotnet restore src/dotnet-mock-server/dotnet-mock-server.csproj
 - dotnet build src/dotnet-mock-server/dotnet-mock-server.csproj
 - dotnet publish src/dotnet-mock-server/dotnet-mock-server.csproj --configuration Release --output build -p:PublishReadyToRun=false -p:PublishSingleFile=true --self-contained true --runtime win-x64
 - rm build/*.pdb
 - mv build/dotnet-mock-server.exe build/nmock.exe	
 
deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file: "build/nmock.exe"
  skip_cleanup: true
  on: master