language: csharp
mono: none
dotnet: 3.1.202

script:
 - dotnet restore
 - dotnet build
 - bash publish.sh
 - rm build/*.pdb
 - mv build/dotnet-mock-server.exe build/nmock.exe	
 
deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file: "build/nmock.exe"
  skip_cleanup: true
  on: master