language: csharp
mono: none
dotnet: 3.1.202

script:
 - dotnet restore src/
 - dotnet build src/
 - dotnet publish src/dotnet-mock-server/dotnet-mock-server.csproj -c Release -o build --no-build -p:PublishReadyToRun=false -p:PublishSingleFile=true -p:PublishTrimmed=true --self-contained true -r win-x64	
 - rm build/*.pdb
 - mv build/dotnet-mock-server.exe build/nmock.exe	
 
deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file: "build/nmock.exe"
  skip_cleanup: true
  on: master